import Head from 'next/head'
import Navbar from '../Header/Navbar'
import styles from './Layout.module.scss'


export default function Layout(props) {
    return (
        <div className={styles.layout}>
            <head>
                <title>My Portfolio</title>
                <meta name="description content" content="Generated by creat next app"/>
            </head>

            <Navbar />

            <main className={styles.main}>{props.children}</main>
        </div>
    )
}
